---
openapi: 3.0.3
info:
  title: MSID/AMSID Management API
  description: API for reading (MSIDs/AMSIDs), inserting (MSIDs/AMSIDs) and
    updating MSID Pair records and their allocation to SBMUs.
  version: 2.0.0
servers:
  - url: https://elexon.my.salesforce.com/services/apexrest/MsidAmsidPairs
    description: Production API
security:
  - BearerAuth: []
paths:
  /Read:
    post:
      summary: /Read Endpoint
      description: >+
        Retrieve existing Msid Pairs in the system given the filter
        criteria (*mandatory **conditional):

        1. partyID * (Party ID as shown in Account Info)

        2. userName * (Email of authorized signatory/contact)

        3. partyAPIKey * (Key as received in email after requesting party key)

        4. msidAmsidRequestID (Batch request ID from a previous Insert or Update operation)

        5. pendingFlag (Filter by status code D, P, PA, S, R)

        6. SVABMUnit ** (Must be an existing SVA BM unit. Required when pendingFlag ≠ R without a MsidAmsidRequestID)

        7. effectiveFromDate ** (required when SVABMUnit populated) 

        8. effectiveToDate ** (required when SVABMUnit populated) 

        9. lastModifiedDate (Can be used with any pendingFlag. Helps refine large result sets near the 5,000-record limit)
                  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/MSIDReadCase1"
                - $ref: "#/components/schemas/MSIDReadCase2"
                - $ref: "#/components/schemas/MSIDReadCase3"
                - $ref: "#/components/schemas/MSIDReadCase4"
      responses:
        "200":
          description: List of MSIDs matching filters
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    MSID_Request_ID:
                      type: string
                      example: "PARTYID_MSID-PAIR-ALLOC-CREATE_20251001171512"
                    MSID_Pair_ID:
                      type: string
                      example: a0sAe000001xJvhIAE
                    Pending_Flag:
                      type: string
                      example: R
                    GSP_Group:
                      type: string
                      example: _P
                    SVA_BM_Unit:
                      type: string
                      example: V__APART001
                    Effective_From_Settlement_Date:
                      type: string
                      format: date
                      example: "2025-04-29"
                    Effective_To_Settlement_Date:
                      type: string
                      format: date
                      example: "2025-07-02"
                    Import_Metering_System:
                      type: string
                      example: "1083772918844"
                    Import_Reject_Reasons:
                      type: string
                      example: "Supplier Role does not exist"
                    Export_Metering_System:
                      type: string
                      example: "1083754918831"
                    Export_Reject_Reasons:
                      type: string
                      example: ""
                    Last_Modified_Date:
                      type: string
                      format: date
                      example: "2025-07-02"                    
        "204":
          description: No content - No MSIDS returned for search criteria          
        "400":
          description: Bad Request - Invalid parameters or limits reached
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidParameters"
                  - $ref: "#/components/schemas/LimitErrorReached"
                  - $ref: "#/components/schemas/PayloadLimit"
                  - $ref: "#/components/schemas/PayloadDatesLimit"
        "401":
          $ref: "#/components/responses/SessionExpiredError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
  /ReadAmsid:
    post:
      summary: /ReadAmsid Endpoint
      description: >+
        Retrieve existing Amsids in the system given the filter criteria
        (*mandatory **conditional):

        1. partyID * (Party ID as shown in Account Info)

        2. userName * (Email of authorized signatory/contact)

        3. partyAPIKey * (Key as received in email after requesting party key)

        4. msidAmsidRequestID * (Batch request ID from a previous Insert or Update operation)

        5. pendingFlag ** (Filter by status code D, P, S, R)        
                  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/AmsidReadCase1"
                - $ref: "#/components/schemas/AmsidReadCase2"
      responses:
        "200":
          description: List of AMSIDs matching filters
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    MSIDAMSID_Request_ID:
                      type: string
                      example: PARTENER_AMSID-PAIR-ALLOC-CREATE_20260303122413
                    Asset_Registration_ID:
                      type: string
                      example: NFL0100
                    Registration_Stage:
                      type: string
                      example: "1"
                    Pending_Flag:
                      type: string
                      example: P
                    SVA_BM_Unit:
                      type: string
                      example: V__HPART001
                    GSP_Group_Id:
                      type: string
                      example: _H
                    AMSID_Pair_EFD:
                      type: string
                      format: date
                      example: "2026-12-10"
                    AMSID_Pair_ETD:
                      type: string
                      format: date
                      example: "2026-12-31"
                    AMVLP:
                      type: string
                      example: PARTENER
                    Address_Line_1:
                      type: string
                      example: SOUTH REDHOUSE ESS
                    Address_Line_2:
                      type: string
                      example: LAND EAST OF REDHOUSE ELECTRICITY
                    Address_Line_3:
                      type: string
                      example: HEATHERYWOOD ROAD
                    Address_Line_4:
                      type: string
                      example: KIRKCALDY
                    Address_Line_5:
                      type: string
                      example: KLDY
                    Address_Line_6:
                      type: string
                      example: KIRLDY
                    Postcode:
                      type: string
                      example: KY13NW
                    Asset_Type:
                      type: string
                      example: BatteryStorage
                    Asset_Voltage:
                      type: string
                      example: "1252"
                    Measurement_Transformer_Indicator:
                      type: string
                      example: F
                    Asset_Capacity:
                      type: string
                      example: "123"
                    Import_AMSID:
                      type: string
                      example: "7700000015338"
                    Export_AMSID:
                      type: string
                      example: "7700000015339"
                    Import_MSID:
                      type: string
                      example: "2000022017780"
                    Export_MSID:
                      type: string
                      example: "2000022017781"
                    Rejection_Reason:
                      type: string
                      example: ""
        "204":
          description: No content - No AMSIDS returned for search criteria          
        "400":
          description: Bad Request - Invalid parameters or limits reached
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidParameters"
                  - $ref: "#/components/schemas/LimitErrorReached"
                  - $ref: "#/components/schemas/PayloadLimit"
                  - $ref: "#/components/schemas/PayloadDatesLimit"
        "401":
          $ref: "#/components/responses/SessionExpiredError"
        "403":
          $ref: "#/components/responses/AuthorizationError"  
  /Insert:
    post:
      summary: /Insert Endpoint
      description: >
        Comma Separated Values JSON with MSID Data fields in order (*)mandatory:


        1. partyID * (Party ID as shown in Account Info)

        2. userName * (Email of authorized signatory/contact)

        3. partyAPIKey * (Key as received in email after requesting party key)

        4. MsidsToInsert * (Comma separated values (12))


        Comma Separated Values JSON with AMSID Data fields in order (*)mandatory:


        1. partyID * (Party ID as shown in Account Info)

        2. userName * (Email of authorized signatory/contact)

        3. partyAPIKey * (Key as received in email after requesting party key)

        4. AmsidsToInsert *  (Comma separated values (22))
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/InsertMsidsRequest"
                - $ref: "#/components/schemas/InsertAmsidsRequest"
      responses:
        "200":
          description: Batch Request Identifier for the MSIDs/AMSIDs atempted to be inserted in the system
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: Accepted
                    requestId:
                      type: string
                      example: PARTTRCY_MSID-PAIR-ALLOC-CREATE_20260303232635
        "202":
          description: Partial success with errors
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Partial202MsidInsert"
                  - $ref: "#/components/schemas/Partial202AMsidInsert" 
        "400":
          description: Bad Request - Invalid parameters or limits reached
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidParameters"
                  - $ref: "#/components/schemas/LimitErrorReached"
                  - $ref: "#/components/schemas/PayloadLimit"
                  - $ref: "#/components/schemas/InsertMSIDSchemaValidation"
                  - $ref: "#/components/schemas/InsertMSIDBusinessValidation"
                  - $ref: "#/components/schemas/InsertAMSIDSchemaValidation"
                  - $ref: "#/components/schemas/InsertAMSIDBusinessValidation"                  
        "401":
          $ref: "#/components/responses/SessionExpiredError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
  /Update:
    post:
      summary: /Update Endpoint
      description: >
        Comma Separated Values string with MSID Data fields in order
        (*)mandatory:


        Effective to Settlement Date

        1. partyID * (Party ID as shown in Account Info)

        2. userName * (Email of authorized signatory/contact)

        3. partyAPIKey * (Key as received in email after requesting party key)

        4. MsidAmsidsToUpdate * (Comma separated values (2))
        
        
        Consent Information

        1. partyID * (Party ID as shown in Account Info)

        2. userName * (Email of authorized signatory/contact)

        3. partyAPIKey * (Key as received in email after requesting party key)

        4. ConsentFlagsToUpdate * (Comma separated values (5))
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/UpdateMSIDETD"
                - $ref: "#/components/schemas/UpdateConsentFlag"
      responses:
        "200":
          description: Batch Request Identifier for the MSIDs atempted to be updated in the system (ETD/customer consent)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: Accepted
                    requestId:
                      type: string
                      example: PARTTRCY_MSID-PAIR-ALLOC-UDPATE_20260303232635
        "202":
          description: Partial success with errors
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Partial202MsidETDUpdate"
                  - $ref: "#/components/schemas/Partial202MsidConsentUpdate" 
        "400":
          description: Bad Request - Invalid parameters or limits reached
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidParameters"
                  - $ref: "#/components/schemas/LimitErrorReached"
                  - $ref: "#/components/schemas/PayloadLimit"
                  - $ref: "#/components/schemas/UpdateSchemaValidation"
                  - $ref: "#/components/schemas/UpdateETDBusinessValidation"
                  - $ref: "#/components/schemas/UpdateConsentFlagBusinessValidation"
        "401":
          $ref: "#/components/responses/SessionExpiredError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    InvalidParameters:
      type: object
      properties:
        message:
          type: string
      example:
        message: Invalid parameters, please check the API documentation
    LimitErrorReached:
      type: object
      properties:
        message:
          type: string
      example:
        message: "Wrong Payload: Maximum number of Row errors reached
          (stored_parameter_number 500)"
    PayloadLimit:
      type: object
      properties:
        message:
          type: string
      example:
        message: Payload too large, exceeded maximum number of records allowed in Update
          API
    PayloadDatesLimit:
      type: object
      properties:
        message:
          type: string
      example:
        message: "Error message: Date Range is greater than the limit specified > 360
          days."
    InsertMSIDSchemaValidation:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
      example:
        status: Payload_Failed
        errors:
        - Row: "1"
          Data: "Incorrect field length: GSP Group."
    InsertMSIDBusinessValidation:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
      example:
        status: Payload_Failed
        errors:
        - Row: "1"
          Data: "The MSID Pair GSP Group must be in the same GSP Group of the associated BM Unit."
    InsertAMSIDSchemaValidation:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
      example:
        status: Payload_Failed
        message: Error count greater than zero but less than error limit (500). Between 1 and 500 record-level errors detected.
        errors:
        - Row: "1"
          Data: "Missing Value: Role Code (must be 2 characters)"
    InsertAMSIDBusinessValidation:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
              assetRegistrationId:
                type: string
      example:
        status: Payload_Failed
        message: Error count greater than zero but less than error limit (500). Between 1 and 500 record-level errors detected.
        errors:
        - Row: "1"
          Data: "The MSID Pair GSP Group must be in the same GSP Group of the associated BM Unit."
          assetRegistrationId: "ASSET001"
    UpdateSchemaValidation:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
      example:
        status: Payload_Failed
        errors:
        - Row: "1"
          Data: "Incorrect field length: MSID Pair ID."
    UpdateETDBusinessValidation:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
      example:
        status: Payload_Failed
        errors:
        - Row: "1"
          Data: "MSID Pair records cannot be changed to a later Effective To Date."
    UpdateConsentFlagBusinessValidation:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
      example:
        status: Payload_Failed
        errors:
        - Row: "1"
          Data: "MSID Pair must be in Pending Status 'S'."
    Partial202MsidInsert:
      type: object
      properties:
        status:
          type: string
        requestId:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string              
      example:
        status: Accepted_with_errors
        requestId: PARTTRCY_MSID-PAIR-ALLOC-CREATE_20260221150528
        errors:
        - Row: "1"
          Data: "The MSID Pair GSP Group must be in the same GSP Group of the associated BM Unit."          
    Partial202AMsidInsert:
      type: object
      properties:
        status:
          type: string
        requestId:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string
              assetRegistrationId:
                type: string
      example:
        status: Payload_Failed
        requestid: PARTTRCY_AMSID-PAIR-ALLOC-CREATE_20260225150528
        message: Error count greater than zero but less than error limit (500). Between 1 and 500 record-level errors detected.
        errors:
        - Row: "1"
          Data: "Invalid Effective From Date: The Effective From Date must be > 5 Working Days from today’s date"
          assetRegistrationId: "ASSET001"
    Partial202MsidETDUpdate:
      type: object
      properties:
        status:
          type: string
        requestId:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string              
      example:
        status: Accepted_with_errors
        requestId: PARTTRCY_MSID-PAIR-ALLOC-UPDATE-MSID-ETD-API_20260303234601
        errors:
        - Row: "1"
          Data: "a0sPv000003CmFAIA0 | MSID Pair record does not exist."
    Partial202MsidConsentUpdate:
      type: object
      properties:
        status:
          type: string
        requestId:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
              Data:
                type: string              
      example:
        status: Accepted_with_errors
        requestId: PARTTRCY_MSID-PAIR-ALLOC-UPDATE-CONSENT-API_20260303234254
        errors:
        - Row: "1"
          Data: "a0sPv0000039s3SIAQ | MSID does not match MSID Pair."
    AuthorizationError:
      type: object
      properties:
        message:
          type: string
      example:
        message: The provided userName and partyID combination is not authorized.
    SessionExpiredError:
      type: object
      properties:
        message:
          type: string
      example:
        message: Session expired or invalid.
    InvalidEndpoint:
      type: object
      properties:
        message:
          type: string
      example:
        message: "Invalid endpoint. Accepted endpoints are: Read, ReadAmsid, Insert, Update"
    MSIDReadCase1:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        msidAmsidRequestID:
          type: string
          maxLength: 100
          example: ALEXTRCI_MSID-PAIR-ALLOC-CREATE_20250804155244
    MSIDReadCase2:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        pendingFlag:
          type: string
          enum:
            - R
          example: R
    MSIDReadCase3:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - SVABMUnit
        - effectiveFromDate
        - effectiveToDate
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        SVABMUnit:
          type: string
          maxLength: 11
          example: V__APART002
        effectiveFromDate:
          type: string
          pattern: ^\d{8}$
          example: 01/08/2025
        effectiveToDate:
          type: string
          pattern: ^\d{8}$
          example: 30/08/2025
    MSIDReadCase4:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - SVABMUnit
        - effectiveFromDate
        - effectiveToDate
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        pendingFlag:
          type: string
          enum:
            - D
            - P
            - PA
            - S
          example: S
        SVABMUnit:
          type: string
          maxLength: 11
          example: V__APART002
        effectiveFromDate:
          type: string
          pattern: ^\d{8}$
          example: 01/08/2025
        effectiveToDate:
          type: string
          pattern: ^\d{8}$
          example: 30/08/2025
    AmsidReadCase1:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - msidAmsidRequestID
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        msidAmsidRequestID:
          type: string
          maxLength: 100
          example: ALEXTRCI_AMSID-PAIR-ALLOC-CREATE_20250804155244
    AmsidReadCase2:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - msidAmsidRequestID
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        msidAmsidRequestID:
          type: string
          maxLength: 100
          example: ALEXTRCI_AMSID-PAIR-ALLOC-CREATE_20250804155244
        pendingFlag:
          type: string
          enum:
            - D
            - P
            - S
            - R
          example: S
    InsertMsidsRequest:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - MsidsToInsert
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        MsidsToInsert:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
                description: Row index
              Data:
                type: string
                description: BMUnitID,GSPGroup,MSIDP,MSIDP,ImportMSID,ImportConsentFlag,ICEFD,ICETD,ExportMSID,ExportConsentFlag,ECEFD,ECETD
            example:
              - Row: "1"
                Data: V__APART002,_A,02/09/2025,20/10/2025,1800061146877,Y,02/09/2025,20/10/2025,1800061146886,Y,02/09/2025,20/10/2025
              - Row: "2"
                Data: V__APART002,_A,02/09/2025,20/10/2025,1800061146877,Y,02/09/2025,20/10/2025,,,,
    InsertAmsidsRequest:
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - AmsidsToInsert
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        AmsidsToInsert:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
                description: Row index
              Data:
                type: string
                description: Asset Registration Id,AMVLP MPID,AMVLP Role,Address Line 1,Address Line 2,Address Line 3,Address Line 4,Address Line 5,Address Line 6,Postcode,GSP Group Id,BM Unit Id,Export AMSID required indicator,Asset type,Asset Voltage,Measurement Transformer Indicator,Asset Capacity,AMSID Pair EFD,AMSID Pair ETD,Measurement Class,Import MSID,Export MSID
            example:
              - Row: "1"
                Data: NFL0100001,PART,AV,ADRESS 1,ADRESS 2,ADRESS 3,ADRESS 4,ADRESS 5,ADRESS 6,KY1 3NW,_M,po,T,Battery Storage,1252,T,123,02/10/2026,31/12/2026,C,2376500474019,1801859241286
              - Row: "2"
                Data: NFL0100001,PART,AV,ADRESS 1,ADRESS 2,ADRESS 3,ADRESS 4,ADRESS 5,ADRESS 6,KY1 3NW,_M,po,F,Battery Storage,1252,F,123,02/10/2026,31/12/2026,C,2376500474019,    
    UpdateMSIDETD:
      title: Update MSID ETD
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - MsidAmsidsToUpdate
      properties:
        partyID:
          type: string
          example: ALEXTRCI
          maxLength: 8
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        MsidAmsidsToUpdate:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
                description: Row index
              Data:
                type: string
                description: MSIDId,EffectiveToSettlementDate
            example:
              - Row: "1"
                Data: a0sAe000002GIr3HAG,10/10/2025
              - Row: "2"
                Data: a0sAe000002GIr3IAG,11/10/2025
    UpdateConsentFlag:
      title: Update MSID Consent Flag
      type: object
      required:
        - partyID
        - userName
        - partyAPIKey
        - ConsentFlagsToUpdate
      properties:
        partyID:
          type: string
          maxLength: 8
          example: ALEXTRCI
        userName:
          type: email
          example: email.api@yaml.com
        partyAPIKey:
          type: string
          maxLength: 255
          example: 68zUNyKoprbKt7ymLN6E/Q==
        ConsentFlagsToUpdate:
          type: array
          items:
            type: object
            properties:
              Row:
                type: string
                description: Row index
              Data:
                type: string
                description: MSIDId,MPAN,ConsentFlag,ConsentEffectiveFromDate,FlowDirection
            example:
              - Row: "1"
                Data: a0sAe000002GIr3HAG,1900071112273,N,10/10/2025,Import
              - Row: "2"
                Data: a0sAe000002GIr3HAG,1900071112273,N,10/10/2025,Export
  responses:
    AuthorizationError:
      description: Authorization failure (invalid API key or unauthorized userName)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthorizationError"
    SessionExpiredError:
      description: Session expired or invalid.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SessionExpiredError"
